version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    container_name: graph-node
    ports:
      - '8900:8000'
      - '8901:8001'
      - '8920:8020'
      - '8930:8030'
      - '8940:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node-match-subgraph-pro
      postgres_pass: let-me-in-match-subgraph-20230518
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'match:http://172.31.34.133:8545'
      GRAPH_LOG: info
      
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    container_name: ipfs
    ports:
      - '5001:5001'
    volumes:
      - ./ipfs:/data/ipfs

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: graph-node-match-subgraph-pro
      POSTGRES_PASSWORD: let-me-in-match-subgraph-20230518
      POSTGRES_DB: graph-node
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"

    volumes:
      - ./postgres:/var/lib/postgresql/data